global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        contimeout 5000
        clitimeout 50000
        srvtimeout 50000

frontend ft_myapp
        bind {{ ip }}:6443
        mode tcp
        default_backend bk_myapp

backend bk_myapp
        mode tcp
        {% for server, addrs in salt['mine.get']('G@roles:controllers', 'internal_ip', 'compound').items() -%}
        server {{ server }} {{ addrs }}:6443 check
        {% endfor -%}
