apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/kube-apiserver:v1.8.2
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-apiserver
      --admission-control=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
      --advertise-address={{ ip }}
      --allow-privileged=true
      --apiserver-count=3
      --audit-log-maxage=30
      --audit-log-maxbackup=3
      --audit-log-maxsize=100
      --audit-log-path=/var/log/audit.log
      --authorization-mode=Node,RBAC
      --bind-address=0.0.0.0
      --client-ca-file=/var/lib/kubernetes/ca.pem
      --enable-swagger-ui=true
      --etcd-cafile=/var/lib/kubernetes/ca.pem
      --etcd-certfile=/var/lib/kubernetes/kubernetes.pem
      --etcd-keyfile=/var/lib/kubernetes/kubernetes-key.pem
      --etcd-servers={{ config }} \
      --event-ttl=1h
      --experimental-encryption-provider-config=/var/lib/kubernetes/encryption-config.yaml
      --insecure-bind-address=127.0.0.1
      --kubelet-certificate-authority=/var/lib/kubernetes/ca.pem
      --kubelet-client-certificate=/var/lib/kubernetes/kubernetes.pem
      --kubelet-client-key=/var/lib/kubernetes/kubernetes-key.pem
      --kubelet-https=true
      --runtime-config=api/all
      --service-account-key-file=/var/lib/kubernetes/ca-key.pem
      --service-cluster-ip-range=10.32.0.0/24
      --service-node-port-range=30000-32767
      --tls-ca-file=/var/lib/kubernetes/ca.pem
      --tls-cert-file=/var/lib/kubernetes/kubernetes.pem
      --tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem
      --v=2 1>> /var/log/kube-apiserver.log 2>&1
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 7080
      hostPort: 7080
      name: http
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /srv/lib
      name: srvlib
      readOnly: true
    - mountPath: /var/lib/kubernetes
      name: varlibkube
      readOnly: true
    - mountPath: /var/log/kube-apiserver.log
      name: logfile
    - mountPath: /var/log/audit.log
      name: logfileaudit
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
    - mountPath: /usr/share/ssl
      name: usrsharessl
      readOnly: true
    - mountPath: /var/ssl
      name: varssl
      readOnly: true
    - mountPath: /usr/ssl
      name: usrssl
      readOnly: true
    - mountPath: /usr/lib/ssl
      name: usrlibssl
      readOnly: true
    - mountPath: /usr/local/openssl
      name: usrlocalopenssl
      readOnly: true
    - mountPath: /etc/openssl
      name: etcopenssl
      readOnly: true
    - mountPath: /etc/pki/tls
      name: etcpkitls
      readOnly: true
  volumes:
  - hostPath:
      path: /srv/lib
    name: srvlib
  - hostPath:
      path: /var/lib/kubernetes
    name: varlibkube
  - hostPath:
      path: /var/log/kube-apiserver.log
    name: logfile
  - hostPath:
      path: /var/log/audit.log
    name: logfileaudit
  - hostPath:
      path: /etc/ssl
    name: etcssl
  - hostPath:
      path: /usr/share/ssl
    name: usrsharessl
  - hostPath:
      path: /var/ssl
    name: varssl
  - hostPath:
      path: /usr/ssl
    name: usrssl
  - hostPath:
      path: /usr/lib/ssl
    name: usrlibssl
  - hostPath:
      path: /usr/local/openssl
    name: usrlocalopenssl
  - hostPath:
      path: /etc/openssl
    name: etcopenssl
  - hostPath:
      path: /etc/pki/tls
    name: etcpkitls
